http:
  routers:
    # Route for Node Exporter
    node-exporter:
      rule: "Host(`node-exporter.${DOMAIN}`)"
      service: "node-exporter-service"
      entryPoints:
        - "websecure"
      tls: {}
    # Route for Traefik's internal API and pprof
    traefik-pprof:
      rule: "PathPrefix(`/`)"
      service: "api@internal"
      entryPoints:
        - "traefik-internal"

  services:
    node-exporter-service:
      loadBalancer:
        servers:
          # Points to the host via the gateway (see extra_hosts in compose)
          - url: "http://host.containers.internal:9100"