graph LR
%% Global Styles
classDef prometheus fill:#3498db,stroke:#2980b9,stroke-width:2px,color:#fff;
classDef pullNode fill:#2ecc71,stroke:#27ae60,stroke-width:1px,color:#fff;
classDef pushNode fill:#e67e22,stroke:#d35400,stroke-width:1px,color:#fff;


%% Core Components
PROM[Prometheus :9090]:::prometheus

%% Direct Pull Jobs
subgraph Direct_Scrape_Jobs [Metrics exporters]
    ALM[Alertmanager :9093]:::pullNode
    ALY[Alloy :12345]:::pullNode
    BBE[Blackbox-Exporter :9115]:::pullNode
    GRA[Grafana :3000]:::pullNode
    LOK[Loki :3100]:::pullNode
    KAR[Karma :8080]:::pullNode
    POD[Podman-Exporter :9882]:::pullNode
    TEM[Tempo :3200]:::pullNode
    GEN[Tempo-generator :3200]:::pushNode
    OTEL[OTel-Collector :8888]:::pullNode
    MIN[MinIO :9000]:::pullNode
    TRF[Traefik :8082]:::pullNode
    KEE[Keep-Backend :8080]:::pullNode
    NOD[Node-Exporter :9100]:::pullNode
end


%% Relationships
PROM -->|Scrape /metrics| ALM
PROM -->|Scrape /metrics| ALY
PROM -->|Scrape /metrics| GRA
PROM -->|Scrape /metrics| LOK
PROM -->|Scrape /metrics| KAR
PROM -->|Scrape /metrics| POD
PROM -->|Scrape /metrics| TEM
PROM ---|Push metrics| GEN
PROM -->|Scrape /metrics| OTEL
PROM -->|Scrape /metrics| MIN
PROM -->|Scrape /metrics| TRF
PROM -->|Scrape /metrics| KEE
PROM -->|Scrape /metrics| NOD
PROM -->|Scrape /probe| BBE



