{
 "title": "Grafana Internals Dashboard",
 "description": "Grafana Internal Metics Dashboards",
 "tags": [ "grafana" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"grafana:3000\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{instance=\"grafana:3000\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{instance=\"grafana:3000\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{instance=\"grafana:3000\"}"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"grafana:3000\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"grafana:3000\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=\"grafana:3000\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"grafana:3000\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Responce Codes and Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Response Statuses",
   "type": "timeseries",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_response_status_total{instance=\"grafana:3000\"}",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total{instance=\"grafana:3000\"}",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total{instance=\"grafana:3000\"}",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "HTTP Req/Resp Details",
   "type": "timeseries",
   "description": "http request counter",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(grafana_http_request_duration_seconds_bucket{job=\"grafana\"}[1m])",
     "legendFormat": "{{handler}} - {{method}} - {{statuscode}}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "timeseries",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_api_login_post_total{instance=\"grafana:3000\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{instance=\"grafana:3000\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  { "title": "Dataproxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Dataproxy Request Quantiles",
   "type": "timeseries",
   "description": "summary for dataproxy request duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"grafana:3000\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"grafana:3000\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dataproxy_request_all_milliseconds{instance=\"grafana:3000\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dataproxy Request Avg [5 min]",
   "type": "timeseries",
   "description": "average dataproxy request duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dataproxy_request_all_milliseconds_sum{instance=\"grafana:3000\"}[5m]) / rate(grafana_api_dataproxy_request_all_milliseconds_count{instance=\"grafana:3000\"}[5m])",
     "legendFormat": "Average Requests Duration"
    }
   ]
  },
  { "title": "Dashboard Get Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{ quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg [5 min]",
   "type": "timeseries",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Save Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg [5 min]",
   "type": "timeseries",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Dashboard Search Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "timeseries",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg [5 min]",
   "type": "timeseries",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{}[5m])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}