{
 "title": "OpenTelemetry & Tempo",
 "description": "OpenTelemetry & Tempo Performance Monitoring",
 "tags": [
  "Traces",
  "OpenTelemetry",
  "Tempo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "otel_service",
    "label": "OTEL_Service",
    "query": {
     "query": "label_values(otelcol_receiver_accepted_spans,service.name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OTEL Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "receiver accepted spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "receiver: {{receiver}} transport: {{transport}}"
    }
   ]
  },
  {
   "title": "🚨 receiver refused spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "receiver: {{receiver}} transport: {{transport}}"
    }
   ]
  },
  {
   "title": "Processor memory rss used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(otelcol_process_runtime_total_sys_memory_bytes{}) by (pod)",
     "legendFormat": "runtime-{{pod}}"
    },
    {
     "expr": "sum(otelcol_process_memory_rss{}) by (pod)",
     "legendFormat": "memory-rss-{{pod}}"
    }
   ]
  },
  {
   "title": "Processor memory_limiter refused spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans_total{}[$__rate_interval])) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "processor batch send size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter send failed spans",
   "type": "timeseries",
   "description": "Check the backend service, <br>e.g: <br>    max_recv_msg_size_mib: 10943040<br>    read_buffer_size: 10943040 ...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) by (service) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter sent spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{}[$__rate_interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_queue_size{}) by (service)",
     "legendFormat": "queue_size: {{service}}"
    },
    {
     "expr": "sum(otelcol_exporter_queue_capacity{}) by (service)",
     "legendFormat": "queue_capacity: {{service}}"
    }
   ]
  },
  { "title": "Tempo Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Querier rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(tempo_querier_worker_request_executed_total{}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Querier ingester live traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(tempo_ingester_live_traces{}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Tempo Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Distributor discarded span",
   "type": "timeseries",
   "description": "Near by 0 is better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(tempo_discarded_spans_total{}[$__rate_interval])) by (reason, tenant)",
     "legendFormat": "tenant: {{tenant}} reason:{{reason}}"
    }
   ]
  },
  {
   "title": "Distributor received spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_received_total{}[$__rate_interval])) by (tenant, service)",
     "legendFormat": "{{tenant}}: {{service}}"
    }
   ]
  },
  {
   "title": "Ingester trace created",
   "type": "timeseries",
   "description": "Tempo Ingester trace created rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_traces_created_total{}[$__rate_interval])) by (pod, tenant)",
     "legendFormat": "{{tenant}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Distributor recived bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_bytes_received_total{}[$__rate_interval])) by (tenant, service)",
     "legendFormat": "{{tenant}}: {{service}}"
    }
   ]
  },
  {
   "title": "Warning reason",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_warnings_total{}[$__interval])) by (tenant, reason, service)",
     "legendFormat": "{{tenant}}: {{reason}} service: {{service}}"
    }
   ]
  },
  { "title": "Tempo Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Ingester created blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_blocks_cleared_total{}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingester flushed blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_blocks_flushed_total{}[$__rate_interval])) by (pod)",
     "legendFormat": "flushed: {{pod}}"
    },
    {
     "expr": "sum(rate(tempo_ingester_failed_flushes_total{}[$__rate_interval])) by (pod)",
     "legendFormat": "failed_flush: {{pod}}"
    }
   ]
  },
  {
   "title": "Blocks compaction & written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_blocks_total{}[$__rate_interval])) by (level)",
     "legendFormat": "compact_rate: level_{{level}}"
    },
    {
     "expr": "sum(rate(tempodb_compaction_bytes_written_total{}[$__rate_interval])) by (level)",
     "legendFormat": "written_bytes: level_{{level}}"
    }
   ]
  },
  {
   "title": "Objects combined & written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{}[$__rate_interval])) by (level)",
     "legendFormat": "combined_rate: level_{{level}}"
    },
    {
     "expr": "sum(rate(tempodb_compaction_objects_written_total{}[$__rate_interval])) by (level)",
     "legendFormat": "written_rate: level_{{level}}"
    }
   ]
  },
  {
   "title": "blocklist length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tempodb_blocklist_length) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ring state members",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tempo_ring_members) by (service, state)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tempo metrics-generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "active processor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 93 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tempo_metrics_generator_active_processors) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pushes & dropped spans in the distributor queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 93 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_queue_pushes_total{}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} push"
    },
    {
     "expr": "sum(rate(tempo_distributor_queue_pushes_failures_total{}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} push failure"
    }
   ]
  },
  {
   "title": "Distributor pushes to the generator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_metrics_generator_pushes_total{}[$__rate_interval])) by (metrics_generator)",
     "legendFormat": "pushes {{metrics_generator}}"
    },
    {
     "expr": "sum(rate(tempo_distributor_metrics_generator_pushes_failures_total{}[$__rate_interval])) by (metrics_generator)",
     "legendFormat": "push failures {{metrics_generator}}"
    }
   ]
  },
  {
   "title": "Discarded spans reason in the generator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(increase(tempo_metrics_generator_spans_discarded_total{}[$__interval])) by (reason, tenant)",
     "legendFormat": "{{tenant}} {{reason}}"
    }
   ]
  },
  {
   "title": "Remote write failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_samples_failed_total{}[$__rate_interval])) by (remote_name, tenant)",
     "legendFormat": "{{tenant}} sample failed {{remote_name}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_samples_dropped_total{}[$__rate_interval])) by (remote_name, tenant, reason)",
     "legendFormat": "{{tenant}} sample dropped {{remote_name}}: {{reason}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_exemplars_failed_total{}[$__rate_interval])) by (remote_name, tenant)",
     "legendFormat": "{{tenant}} exemplar failed {{remote_name}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_exemplars_dropped_total{}[$__rate_interval])) by (remote_name, tenant, reason)",
     "legendFormat": "{{tenant}} exemplar dropped {{remote_name}}: {{reason}}"
    }
   ]
  },
  {
   "title": "Max active series limited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(tempo_metrics_generator_registry_series_limited_total{}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} limited"
    }
   ]
  },
  {
   "title": "Remote write failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "traces_service_graph_request_failed_total",
     "legendFormat": "{{tenant}} sample failed {{remote_name}}"
    }
   ]
  },
  {
   "title": "SpanMetrics span call rate by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total[$__rate_interval])) by(service,tenant)",
     "legendFormat": "{{tenant}} . {{service}}"
    }
   ]
  },
  {
   "title": "ServiceGraph client request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum(rate(traces_service_graph_request_total[$__rate_interval])) by (tenant, client)",
     "legendFormat": "{{tenant}} . {{client}}"
    }
   ]
  }
 ]
}