receivers:
  # The OTLP receiver is required for the OpenTelemetry Collector to receive traces from the applications instrumented with OpenTelemetry and send them to Tempo. It allows the collector to accept data in the OpenTelemetry Protocol (OTLP) format, which is a standard format for telemetry data.
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Send Traces to Tempo
  otlp_grpc/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # (Optional) For debugging logging to stdout
  debug:
    verbosity: detailed

service:
  # Monitor the collector itself (metrics op poort 8888
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]